public class DataTypesDemo {
    byte classByte;
    short classShort;
    int classInt;
    long classLong;
    float classFloat;
    double classDouble;
    char classChar;
    boolean classBoolean;
    Byte wrapperByte;
    Short wrapperShort;
    Integer wrapperInt;
    Long wrapperLong;
    Float wrapperFloat;
    Double wrapperDouble;
    Character wrapperChar;
    Boolean wrapperBoolean;
    public static void main(String[] args) {
        DataTypesDemo demo = new DataTypesDemo();
        System.out.println("=== ПРАКТИКА #1: Все типы данных ===");
        System.out.println("\n--- Целочисленные типы ---");
        byte b = 127;                
        short s = 32767;             
        int i = 2147483647;            
        long l = 9223372036854775807L; 
        System.out.println("byte: " + b);
        System.out.println("short: " + s);
        System.out.println("int: " + i);
        System.out.println("long: " + l);
        System.out.println("\n--- Типы с плавающей точкой ---");
        float f = 3.1415926535f;        
        double d = 3.14159265358979323846;
        System.out.println("float: " + f);
        System.out.println("double: " + d);
        System.out.println("\n--- Символьный тип ---");
        char c = 'A';                  
        char c2 = 65;                     
        char c3 = '\u0041';           
        System.out.println("char 'A': " + c);
        System.out.println("char 65: " + c2);
        System.out.println("char \\u0041: " + c3);
        System.out.println("\n--- Булевский тип ---");
        boolean boolTrue = true;
        boolean boolFalse = false;
        System.out.println("boolean true: " + boolTrue);
        System.out.println("boolean false: " + boolFalse);
        System.out.println("\n--- Нулевые значения членов класса ---");
        System.out.println("byte (по умолчанию): " + demo.classByte);    
        System.out.println("short (по умолчанию): " + demo.classShort);    
        System.out.println("int (по умолчанию): " + demo.classInt);       
        System.out.println("long (по умолчанию): " + demo.classLong);      
        System.out.println("float (по умолчанию): " + demo.classFloat);  
        System.out.println("double (по умолчанию): " + demo.classDouble); 
        System.out.println("char (по умолчанию): [" + demo.classChar + "]"); 
        System.out.println("char (код): " + (int)demo.classChar);         
        System.out.println("boolean (по умолчанию): " + demo.classBoolean); 
        System.out.println("\n--- Классы-оболочки (по умолчанию null) ---");
        System.out.println("Byte wrapper: " + demo.wrapperByte);        
        System.out.println("Integer wrapper: " + demo.wrapperInt);    
        System.out.println("Double wrapper: " + demo.wrapperDouble);      
        System.out.println("Boolean wrapper: " + demo.wrapperBoolean);   
        System.out.println("\n--- Локальная переменная ---");
        int localVar;        
        localVar = 42;         
        System.out.println("localVar после инициализации: " + localVar);
        System.out.println("\n--- Автоупаковка/распаковка ---");
        Integer wrapped = 100;  
        int unwrapped = wrapped;     
        System.out.println("wrapped Integer: " + wrapped);
        System.out.println("unwrapped int: " + unwrapped);
    }
}
